PREFIX ?= fd00::1/64

connect-router: $(TUNSLIP6)
ifeq ($(PORT),)
	sudo $(TUNSLIP6) $(PREFIX)
else
	sudo $(TUNSLIP6) -s $(PORT) $(PREFIX)
endif

connect-router-cooja: $(TUNSLIP6)
	sudo $(TUNSLIP6) -a 127.0.0.1 $(PREFIX)
